# DATA ENCODING ---
Computers "speak" in numbers, but humans often collect data in words (Categories). Encoding is the process of converting those words into a format that a machine learning model can perform math on.
   # types 
   1 . One-Hot Encoding is a specific type of encoding used for Nominal Data. "Nominal" means the categories have no logical rank or order.
   
   The "Light Switch" Logic:Imagine you have a column called Color with three options: Red, Green, and Blue.

   Instead of one column with different words, OHE creates three "light switches" (new columns).If the color is Red, the Red switch is ON (1) and the others are OFF (0).If the color is Green, only the Green switch is 1.Why use OHE instead of just 1, 2, 3?

   If you use numbers ($Red=1, Green=2, Blue=3$), the computer thinks Green is "twice as much" as Red, or that Blue is "greater than" Green. This is a mathematical bias. OHE prevents this by keeping all categories on an equal playing field.

In [9]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [10]:
#create a dataframe 
df = pd.DataFrame ({ 
    'color': ['red', 'blue','green', 'green' , 'red', 'blue']

})


In [11]:
#create a instance of onehotencoder 

encoder = OneHotEncoder()

In [12]:
#perform fit and transform here 
encoded = encoder.fit_transform(df[['color']]).toarray()
#[[]] 2d is necessary here , toarray () shows us the sparse matrix hare 

In [13]:
encoded
#here blue got ist position because of alphabitical order then other two by same 
#and here we converted the categorical into numerical vali=ue

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

# label encoding 
While OHE creates many new columns, Label Encoding keeps everything in a single column by assigning each category a unique integer (number)
 How it works 
 APLLE AS 1 
 BANANA AS 2 
 MANGO AS 3 
     this albel as in alphabetical oder

In [14]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

lbl_encoder.fit_transform(df[['color']])

# it assigned 2 for red , 1 for green and 0 for blue 
# here we use [] single brackets 

c:\Users\USER\OneDrive\Desktop\AI ,ML\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

# ORDINAL ENCODING 

In Label Encoding, the computer chooses the numbers alphabetically 

(e.g., "Large" might become 0 and "Small" might become 2). 

In Ordinal Encoding, you can force "Small" to be 0, "Medium" to be 1, and "Large" to be 2.



In [15]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

df = pd.DataFrame ({
 
 'size' : ['small' , 'large' ,'medium','medium', 'small', 'large']

})

In [16]:
#creating an instance of ordinal encoding and then perform fittransform
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])
encoder.fit_transform(df[['size']])

array([[0.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.]])

### TARGET GUIDED ORDINAL ENCODING 
Target Guided Ordinal Encoding is a sophisticated feature engineering technique used to transform categorical variables into numerical ones by leveraging the relationship between the category and the target variable.


Unlike standard Ordinal Encoding (where you manually assign ranks like Small=1, Medium=2) or Label Encoding (which often assigns numbers alphabetically), this method calculates the order based on the target’s statistics.

In [2]:
import numpy as np 
import pandas as pd
#create a dataframe with a categorical values and target values

df = pd.DataFrame ({

    'city' :[ 'mehind' , 'nowshara' ,'khiram' , 'sirhama' , 'mehind' , 'khiram'],

     'price' : [1000, 3000 , 2000 , 1200, 8000, 2300]
})
#so above you can see mehind and khiram are repeated so now we will see their mean then consider only one 

In [ ]:
meanprice = df.groupby('city')['price'].mean().to_dict()

In [4]:
meanprice

<bound method Series.to_dict of city
khiram      2150.0
mehind      4500.0
nowshara    3000.0
sirhama     1200.0
Name: price, dtype: float64>

In [7]:
df['city_encoded']= df['city'].map(meanprice)

In [8]:
df

,city,price,city_encoded
0,mehind,1000,4500.0
1,nowshara,3000,3000.0
2,khiram,2000,2150.0
3,sirhama,1200,1200.0
4,mehind,8000,4500.0
5,khiram,2300,2150.0
